#
# Generated by Appeal's processor emitter (appeal/codegen3.py).
# A compiled parser MODULE that wears the Appeal API: import it AS appeal
# and your program is unchanged.  Imports only appeal.processor and
# appeal.runtime (the stdlib-only core).  Regenerate rather than edit.

import sys

from appeal.processor import Converter, Repeat, Processor, dispatch
from appeal.runtime import (
    UsageError, split, validate, validate_range, counter, accumulator,
    mapping, file, optional,
    )

_callables = {}     # command word -> the user's function, bound at @command


class Converter_report(Converter):
    def __init__(self):
        Converter.__init__(self, _callables['report'])
    def register(self, processor):
        processor.prepend([
            self.Option('-u', 'units', str),
            self.Option('--units', 'units', str),
            self.Option('-v', 'verbose', bool),
            self.Option('--verbose', 'verbose', bool),
            self.Argument('city', str, True),
        ])

class Converter_forecast(Converter):
    def __init__(self):
        Converter.__init__(self, _callables['forecast'])
    def register(self, processor):
        processor.prepend([
            self.Argument('city', str, True),
            self.Argument('days', int, False),
        ])

class Converter_sync(Converter):
    def __init__(self):
        Converter.__init__(self, _callables['sync'])
    def register(self, processor):
        processor.prepend([
            self.Option('-v', 'verbose', counter(max=None, step=1)),
            self.Option('--verbose', 'verbose', counter(max=None, step=1)),
            self.Option('-t', 'tag', accumulator[str]),
            self.Option('--tag', 'tag', accumulator[str]),
            self.Option('-m', 'mode', validate('fast', 'safe', type=str)),
            self.Option('--mode', 'mode', validate('fast', 'safe', type=str)),
            self.Argument('source', split(':'), True),
        ])

_COMMANDS = {
    'report': Converter_report,
    'forecast': Converter_forecast,
    'sync': Converter_sync,
}

class Appeal:
    "The compiled parser wearing the Appeal API (parse + dispatch only)."
    def __init__(self, name=None, *, version=None):
        self.name = name
        self.version = version
        self.commands = {}

    def command(self, name=None):
        def register(fn):
            word = name or fn.__name__
            _callables[word] = fn
            self.commands[word] = _COMMANDS[word]
            return fn
        return register

    def process(self, argv):
        return dispatch(self.commands, list(argv))

    def main(self, argv=None):
        argv = sys.argv[1:] if argv is None else list(argv)
        try:
            result = self.process(argv)
        except UsageError as e:
            print(f'{self.name or "error"}: {e}', file=sys.stderr)
            return 2
        return result if isinstance(result, int) else 0
