#
# Generated by Appeal's emitter (appeal/compile.py).
# A compiled parser MODULE that wears the Appeal API: import it AS appeal
# and your program is unchanged.  Imports only appeal.runtime (the
# stdlib-only core).  Regenerate rather than edit.

from appeal.runtime import (
    Converter, appeal_class, split, validate, validate_range, counter,
    accumulator, mapping, file, optional,
    )

Appeal = appeal_class(baked_fingerprint='2f2808dac5cf0aac4523f100fe6a3649c4846fae',
                      default_mappings_fp='496c9a6acedd25efbe35bb420b68ec4673d76edd',
                      default_options_fp='5c7d671508534e3a249d37a138442b740dc2c7d2')

@Appeal._converter('report')
class Converter_report(Converter):
    _fingerprint = 'ab1c61e4bbf05e6c5cf7a5530f753825319b482d'
    def register(self, processor):
        processor.prepend([
            self.Option('units', str, '-u', '--units'),
            self.Option('verbose', bool, '-v', '--verbose'),
            self.Argument('city', str, required=True),
        ])

@Appeal._converter('forecast')
class Converter_forecast(Converter):
    _fingerprint = '5fd9199908d88fe5942aba920086e0d97cd6956d'
    def register(self, processor):
        processor.prepend([
            self.Argument('city', str, required=True),
            self.Argument('days', int, required=False),
        ])

@Appeal._converter('sync')
class Converter_sync(Converter):
    _fingerprint = '87f6f4c00ee4e9fb09fee6637fbd71ffc419c54b'
    def register(self, processor):
        annotations = type(self).converter.__annotations__
        processor.prepend([
            self.Option('verbose', annotations['verbose'], '-v', '--verbose'),
            self.Option('tag', annotations['tag'], '-t', '--tag'),
            self.Option('mode', annotations['mode'], '-m', '--mode'),
            self.Argument('source', annotations['source'], required=True),
        ])
