#
# Generated by Appeal's processor emitter (appeal/codegen3.py).
# A compiled parser MODULE that wears the Appeal API: import it AS appeal
# and your program is unchanged.  Imports only appeal.processor and
# appeal.runtime (the stdlib-only core).  Regenerate rather than edit.

import sys

from appeal.processor import Converter, Repeat, Processor, execute
from appeal.runtime import (
    UsageError, split, validate, validate_range, counter, accumulator,
    mapping, file, optional,
    )

commands = {}


def command(name):
    def command(cls):
        commands[name] = cls
        return cls
    return command


@command('report')
class Converter_report(Converter):
    def register(self, processor):
        processor.prepend([
            self.Option('units', str, '-u', '--units'),
            self.Option('verbose', bool, '-v', '--verbose'),
            self.Argument('city', str, required=True),
        ])

@command('forecast')
class Converter_forecast(Converter):
    def register(self, processor):
        annotations = type(self).converter.__annotations__
        processor.prepend([
            self.Argument('city', str, required=True),
            self.Argument('days', annotations['days'], required=False),
        ])

@command('sync')
class Converter_sync(Converter):
    def register(self, processor):
        annotations = type(self).converter.__annotations__
        processor.prepend([
            self.Option('verbose', annotations['verbose'], '-v', '--verbose'),
            self.Option('tag', annotations['tag'], '-t', '--tag'),
            self.Option('mode', annotations['mode'], '-m', '--mode'),
            self.Argument('source', annotations['source'], required=True),
        ])

class Appeal:
    "The compiled parser wearing the Appeal API (parse + dispatch only)."
    def __init__(self, name=None, *, version=None):
        self.name = name
        self.version = version
        self.commands = {}

    def command(self, name=None):
        def command(converter):
            nonlocal name
            name = name or converter.__name__
            cls = commands[name]
            cls.converter = converter
            self.commands[name] = cls
            return converter
        return command

    def process(self, args):
        return execute(self.commands, list(args))

    def main(self, args=None):
        args = sys.argv[1:] if args is None else list(args)
        try:
            result = self.process(args)
        except UsageError as e:
            print(f'{self.name or "error"}: {e}', file=sys.stderr)
            return 2
        return result if isinstance(result, int) else 0
