#
# weather -- command-line parsing (report, forecast, sync)
# Generated by Appeal: a compiled parser MODULE, wearing the Appeal API.
# Import it AS appeal and your program is unchanged:
#
#     try:
#         import compiled as appeal
#     except ImportError:
#         import appeal
#
# Imports appeal.runtime (the stdlib-only core) and bakes ONLY
# parse+dispatch--no help or usage text.  Help and errors render
# live through full Appeal (imported only when one fires).
# Regenerate rather than edit.


# ---- the appeal runtime (stdlib-only core) ----

import sys

from appeal.runtime import (
    parse_tokens,
    convert,
    accumulate,
    collect_mapping,
    fold,
    call_converter,
    convert_value,
    window_options,
    greedy_sizes,
    did_you_mean,
    check_count,
    absorb_take,
    scopes_for,
    sibling_scopes,
    scoped_forces,
    scoped_window,
    scoped_resolve,
    scoped_rewind,
    scoped_next,
    run_command_set,
    UsageError,
    Command,
    _CompiledHelp,
    optional,
    split,
    validate,
    validate_range,
    counter,
    file,
    accumulator,
    mapping,
    )

from appeal.precompile import compiled_appeal


# ---- your program (bound live at registration) ----

_option_value = optional[str]
def _default_help(topic):
    parse_help([topic] if topic else [])
_validate = validate('fast', 'safe', type=str)
_split = split(':')
_counter = counter(max=None, step=1)
_accumulator = accumulator[str]


# ---- generated parser ----

def _COMPLETE_weather():
    return {'options': {'-h': ('--help', 1, False), '--help': ('--help', 1, False), '-V': ('--version', 0, False), '--version': ('--version', 0, False)}, 'help': (), 'values': {'--help': (_option_value,)}, 'operands': (), 'repeat': None, 'minimum': 0, 'maximum': 0}
_OPTIONS_weather = {'-h': ('--help', 'group', 0, 1), '--help': ('--help', 'group', 0, 1), '-V': ('--version', 'flag', True), '--version': ('--version', 'flag', True)}

def _fill_option_value(operands, i, remaining, given):
    # reads exactly `remaining` arguments and builds
    # option_value(value)
    # value: takes 1, or is skipped; the slots after it need 0
    if remaining - 1 == 0:
        value = convert(str, operands[i], 'value', None)
        i += 1
        remaining -= 1
    else:
        value = None
    return _option_value(value), i

def scan_weather(argv, command_words=None):
    # the global command: its arguments end at the first
    # operand naming a command (or at the maximum)
    operands, given, rest = parse_tokens(argv, _OPTIONS_weather, None, command_split=(0, 0, frozenset({'version', 'help', 'report', 'sync', 'forecast'})))
    if given.pop('-V', False) or given.pop('--version', False):
        print('1.0')
        raise SystemExit(0)
    _topic = None
    if _topic is None and '-h' in given:
        _topic = list(given.pop('-h'))
    if _topic is None and '--help' in given:
        _topic = list(given.pop('--help'))
    if _topic is not None:
        _default_help(_topic[0] if _topic else '')
        raise SystemExit(0)
    check_count(len(operands), 0, 0, {0}, None)
    if '--help' in given:
        check_count(len(given['--help']), 0, 1, {0, 1}, None, what="option --help", param='--help')
    return operands, given, rest, None

def run_weather(operands, given, positions=None, env=None, command=None):
    n = len(operands)
    i = 0
    remaining = n
    help = None
    if '--help' in given:
        help = _fill_option_value(list(given['--help']), 0, len(given['--help']), given)[0]
    version = given.get('--version', False)
    if version:
        print('1.0')
        raise SystemExit(0)
    return None

_CMD_weather = Command('weather', scan=scan_weather, run=run_weather)
def parse_weather(argv):
    operands, given, rest, positions = scan_weather(argv)
    return run_weather(operands, given, positions, command=_CMD_weather), rest



def _COMPLETE_report():
    return {'options': {'-u': ('--units', 1, False), '--units': ('--units', 1, False), '-v': ('--verbose', 0, False), '--verbose': ('--verbose', 0, False)}, 'help': ('-h', '--help'), 'values': {'--units': (str,)}, 'operands': (str,), 'repeat': None, 'minimum': 1, 'maximum': 1}
_OPTIONS_report = {'-u': ('--units', 'value'), '--units': ('--units', 'value'), '-v': ('--verbose', 'flag', True), '--verbose': ('--verbose', 'flag', True), '-h': ('--help', 'flag'), '--help': ('--help', 'flag')}

def scan_report(argv, command_words=None):
    if command_words is None:
        operands, given = parse_tokens(argv, _OPTIONS_report, None)
        rest = []
    else:
        # cycling: the boundary is greedy saturation--the
        # first non-option token after 1 argument is
        # the next command word, whatever it looks like
        operands, given, rest = parse_tokens(argv, _OPTIONS_report, None, command_split=(1, 1, command_words))
    if given.get('--help'):
        # help outranks a malformed line (pinned order)
        return operands, given, rest, None
    check_count(len(operands), 1, 1, {1}, None)
    return operands, given, rest, None

def run_report(operands, given, positions=None, env=None, command=None):
    if given.pop('--help', False):
        raise _CompiledHelp(command)
    n = len(operands)
    i = 0
    remaining = n
    city = convert(str, operands[i], 'city', None)
    i += 1
    remaining -= 1
    units = 'C'
    if '--units' in given:
        units = convert_value((str,), given['--units'], 'units', None)
    verbose = given.get('--verbose', False)
    return command.callable(city, units=units, verbose=verbose)

_CMD_report = Command('report', scan=scan_report, run=run_report, fingerprint=(1, 0, 2, False, False, ('city', 'units', 'verbose'), 'None', "{'units': 'C', 'verbose': False}", ()), options=(), arguments=())
def parse_report(argv):
    operands, given, rest, positions = scan_report(argv)
    return run_report(operands, given, positions, command=_CMD_report)



def _COMPLETE_forecast():
    return {'options': {}, 'help': ('-h', '--help'), 'values': {}, 'operands': (str, int), 'repeat': None, 'minimum': 1, 'maximum': 2}
_OPTIONS_forecast = {'-h': ('--help', 'flag'), '--help': ('--help', 'flag')}

def scan_forecast(argv, command_words=None):
    if command_words is None:
        operands, given = parse_tokens(argv, _OPTIONS_forecast, None)
        rest = []
    else:
        # cycling: the boundary is greedy saturation--the
        # first non-option token after 2 arguments is
        # the next command word, whatever it looks like
        operands, given, rest = parse_tokens(argv, _OPTIONS_forecast, None, command_split=(2, 2, command_words))
    if given.get('--help'):
        # help outranks a malformed line (pinned order)
        return operands, given, rest, None
    check_count(len(operands), 1, 2, {1, 2}, None)
    return operands, given, rest, None

def run_forecast(operands, given, positions=None, env=None, command=None):
    if given.pop('--help', False):
        raise _CompiledHelp(command)
    n = len(operands)
    i = 0
    remaining = n
    city = convert(str, operands[i], 'city', None)
    i += 1
    remaining -= 1
    # days: takes 1, or is skipped; the slots after it need 0
    if remaining - 1 == 0:
        days = convert(int, operands[i], 'days', None)
        i += 1
        remaining -= 1
    else:
        days = 3
    return command.callable(city, days)

_CMD_forecast = Command('forecast', scan=scan_forecast, run=run_forecast, fingerprint=(2, 0, 0, False, False, ('city', 'days'), '(3,)', 'None', (('days', 'builtins.int'),)), options=(), arguments=())
def parse_forecast(argv):
    operands, given, rest, positions = scan_forecast(argv)
    return run_forecast(operands, given, positions, command=_CMD_forecast)



def _COMPLETE_sync():
    return {'options': {'-v': ('--verbose', 0, True), '--verbose': ('--verbose', 0, True), '-t': ('--tag', 1, True), '--tag': ('--tag', 1, True), '-m': ('--mode', 1, False), '--mode': ('--mode', 1, False)}, 'help': ('-h', '--help'), 'values': {'--tag': (str,), '--mode': (_validate,)}, 'operands': (_split,), 'repeat': None, 'minimum': 1, 'maximum': 1}
_OPTIONS_sync = {'-v': ('--verbose', 'fold', 0, 0), '--verbose': ('--verbose', 'fold', 0, 0), '-t': ('--tag', 'fold', 1, 1), '--tag': ('--tag', 'fold', 1, 1), '-m': ('--mode', 'value'), '--mode': ('--mode', 'value'), '-h': ('--help', 'flag'), '--help': ('--help', 'flag')}

def scan_sync(argv, command_words=None):
    if command_words is None:
        operands, given = parse_tokens(argv, _OPTIONS_sync, None)
        rest = []
    else:
        # cycling: the boundary is greedy saturation--the
        # first non-option token after 1 argument is
        # the next command word, whatever it looks like
        operands, given, rest = parse_tokens(argv, _OPTIONS_sync, None, command_split=(1, 1, command_words))
    if given.get('--help'):
        # help outranks a malformed line (pinned order)
        return operands, given, rest, None
    check_count(len(operands), 1, 1, {1}, None)
    return operands, given, rest, None

def run_sync(operands, given, positions=None, env=None, command=None):
    if given.pop('--help', False):
        raise _CompiledHelp(command)
    n = len(operands)
    i = 0
    remaining = n
    source = convert(_split, operands[i], 'source', None)
    i += 1
    remaining -= 1
    verbose = 0
    if '--verbose' in given:
        verbose = fold(_counter, (), given['--verbose'], 0, 'verbose', None)
    tag = ()
    if '--tag' in given:
        tag = fold(_accumulator, (str,), given['--tag'], (), 'tag', None)
    mode = 'safe'
    if '--mode' in given:
        mode = convert_value((_validate,), given['--mode'], 'mode', None)
    return command.callable(source, verbose=verbose, tag=tag, mode=mode)

_CMD_sync = Command('sync', scan=scan_sync, run=run_sync, fingerprint=(1, 0, 3, False, False, ('source', 'verbose', 'tag', 'mode'), 'None', "{'verbose': 0, 'tag': (), 'mode': 'safe'}", (('mode', "recipe:call:validate:('fast', 'safe'):{'type': <class 'str'>}"), ('source', "recipe:call:split:(':',):{}"), ('tag', "recipe:subscript:accumulator:(<class 'str'>,):{}"), ('verbose', "recipe:call:counter:():{'max': None, 'step': 1}"))), options=(), arguments=())
def parse_sync(argv):
    operands, given, rest, positions = scan_sync(argv)
    return run_sync(operands, given, positions, command=_CMD_sync)



def _COMPLETE_command_set():
    return {'commands': {'report': _COMPLETE_report(), 'forecast': _COMPLETE_forecast(), 'sync': _COMPLETE_sync(), 'version': {'options': {}, 'help': (), 'values': {}, 'operands': (), 'repeat': None, 'minimum': 0, 'maximum': 0}}, 'global': dict(_COMPLETE_weather(), help=()), 'minimum': 0, 'auto_help': True, 'repeat': False}

_VERSION = '1.0'
def parse_version(argv):
    if argv:
        raise UsageError("version takes no arguments", None)
    print(_VERSION)

def parse_help(argv):
    # `help` alone: the listing; `help CMD`: CMD's
    # --help; the auto commands and nested parents
    # describe themselves
    if not argv:
        raise _CompiledHelp(None, 0)
        return
    if argv[0] == 'help':
        print('Print usage documentation on a specific command.')
        return
    if argv[0] == 'version':
        print("Print the program's version.")
        return
    entry = _COMMANDS.get(argv[0])
    if entry is None:
        raise UsageError(f"unknown command {argv[0]!r}"
                         f"{did_you_mean(argv[0], _COMMANDS)}",
                         None)
    if entry.subcommands:
        # a nested set: drive its parent -h, which raises
        # the help signal tagged with the parent command
        operands, given, rest, positions = entry.scan(['--help'])
        return entry.run(operands, given, positions, command=entry)
    operands, given, rest, positions = entry.scan(['--help'])
    return entry.run(operands, given, positions, command=entry)

def _print_listing():
    raise _CompiledHelp(None, 0)

def _print_terse_listing():
    raise _CompiledHelp(None, 1)

_COMMANDS = {'report': _CMD_report, 'forecast': _CMD_forecast, 'sync': _CMD_sync, 'version': Command('version', fused=parse_version), 'help': Command('help', fused=parse_help)}
_COMMAND_WORDS = frozenset(('forecast', 'help', 'report', 'sync', 'version',))

def parse_command_set(argv):
    return run_command_set(argv, _CMD_weather, _COMMANDS, None, repeat=False, words=_COMMAND_WORDS, listing=_print_terse_listing)


# ---- drift fingerprints, folded onto the Commands ----

_CMD_report.converters = ()
_CMD_forecast.converters = ()
_CMD_sync.converters = ()


# ---- the Appeal your program imports ----
_SPEC = {'program': 'weather', 'entry': 'parse_command_set', 'complete': '_COMPLETE_command_set', 'templates': 'usage: {usage}\n\n{summary}\n\n{doc}\n\n## Arguments\n{arguments}\n\n## Options\n{options}\n\n## Commands\n{commands}\n', 'config': {'name': 'weather', 'version': '1.0', 'repeat': False, 'margin': 79, 'positional_argument_usage_format': '<{name.upper()}>', 'doc': None, 'templates': 'usage: {usage}\n\n{summary}\n\n{doc}\n\n## Arguments\n{arguments}\n\n## Options\n{options}\n\n## Commands\n{commands}\n'}, 'commands': '_COMMANDS', 'global': None, 'default': None}

Appeal = compiled_appeal(_SPEC, globals())
